[project]
name = "diary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django>=3.2,<3.3",
    "django-widget-tweaks>=1.5.0",
]
